/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheetsRouteImport } from './routes/sheets'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FollowUpRouteImport } from './routes/follow-up'
import { Route as EmailScanRouteImport } from './routes/email-scan'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutoApplyRouteImport } from './routes/auto-apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SheetsRoute = SheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpRoute = FollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailScanRoute = EmailScanRouteImport.update({
  id: '/email-scan',
  path: '/email-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoApplyRoute = AutoApplyRouteImport.update({
  id: '/auto-apply',
  path: '/auto-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-apply': typeof AutoApplyRoute
  '/dashboard': typeof DashboardRoute
  '/email-scan': typeof EmailScanRoute
  '/follow-up': typeof FollowUpRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sheets': typeof SheetsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-apply': typeof AutoApplyRoute
  '/dashboard': typeof DashboardRoute
  '/email-scan': typeof EmailScanRoute
  '/follow-up': typeof FollowUpRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sheets': typeof SheetsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-apply': typeof AutoApplyRoute
  '/dashboard': typeof DashboardRoute
  '/email-scan': typeof EmailScanRoute
  '/follow-up': typeof FollowUpRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sheets': typeof SheetsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auto-apply'
    | '/dashboard'
    | '/email-scan'
    | '/follow-up'
    | '/settings'
    | '/setup'
    | '/sheets'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auto-apply'
    | '/dashboard'
    | '/email-scan'
    | '/follow-up'
    | '/settings'
    | '/setup'
    | '/sheets'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/auto-apply'
    | '/dashboard'
    | '/email-scan'
    | '/follow-up'
    | '/settings'
    | '/setup'
    | '/sheets'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoApplyRoute: typeof AutoApplyRoute
  DashboardRoute: typeof DashboardRoute
  EmailScanRoute: typeof EmailScanRoute
  FollowUpRoute: typeof FollowUpRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SheetsRoute: typeof SheetsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sheets': {
      id: '/sheets'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof SheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-up': {
      id: '/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof FollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-scan': {
      id: '/email-scan'
      path: '/email-scan'
      fullPath: '/email-scan'
      preLoaderRoute: typeof EmailScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-apply': {
      id: '/auto-apply'
      path: '/auto-apply'
      fullPath: '/auto-apply'
      preLoaderRoute: typeof AutoApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoApplyRoute: AutoApplyRoute,
  DashboardRoute: DashboardRoute,
  EmailScanRoute: EmailScanRoute,
  FollowUpRoute: FollowUpRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SheetsRoute: SheetsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
